

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1281, 851)
        MainWindow.setStyleSheet("background-color: none;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1281, 851))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.day = QtWidgets.QWidget()
        self.day.setStyleSheet("border-radius: 15px;")
        self.day.setObjectName("day")
        self.frame = QtWidgets.QFrame(self.day)
        self.frame.setGeometry(QtCore.QRect(0, 0, 341, 861))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.nameapp = QtWidgets.QLabel(self.frame)
        self.nameapp.setGeometry(QtCore.QRect(20, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        self.nameapp.setFont(font)
        self.nameapp.setStyleSheet("color: rgb(91, 91, 91);")
        self.nameapp.setObjectName("nameapp")
        self.profile = QtWidgets.QLabel(self.frame)
        self.profile.setGeometry(QtCore.QRect(20, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.profile.setFont(font)
        self.profile.setStyleSheet("background-color: #00a300;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.profile.setAlignment(QtCore.Qt.AlignCenter)
        self.profile.setObjectName("profile")
        self.nameuser = QtWidgets.QLabel(self.frame)
        self.nameuser.setGeometry(QtCore.QRect(70, 70, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        self.nameuser.setFont(font)
        self.nameuser.setObjectName("nameuser")
        self.myday1 = QtWidgets.QPushButton(self.frame)
        self.myday1.setGeometry(QtCore.QRect(0, 140, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.myday1.setFont(font)
        self.myday1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.myday1.setStyleSheet("border: 0px;\n"
"color: #647783;\n"
"background-color: rgb(248, 249, 250);")
        self.myday1.setObjectName("myday1")
        self.myday_icon = QtWidgets.QLabel(self.frame)
        self.myday_icon.setGeometry(QtCore.QRect(20, 140, 41, 61))
        self.myday_icon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.myday_icon.setStyleSheet("background-color: none;")
        self.myday_icon.setText("")
        self.myday_icon.setPixmap(QtGui.QPixmap("images/my day.png"))
        self.myday_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.myday_icon.setObjectName("myday_icon")
        self.show_pag_select = QtWidgets.QLabel(self.frame)
        self.show_pag_select.setGeometry(QtCore.QRect(10, 140, 21, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        self.show_pag_select.setFont(font)
        self.show_pag_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_pag_select.setStyleSheet("color: #647783;\n"
"background-color: none;")
        self.show_pag_select.setObjectName("show_pag_select")
        self.comp1 = QtWidgets.QPushButton(self.frame)
        self.comp1.setGeometry(QtCore.QRect(0, 200, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.comp1.setFont(font)
        self.comp1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comp1.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: #000000;\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(248, 248, 248);\n"
"}")
        self.comp1.setObjectName("comp1")
        self.comp_icon = QtWidgets.QLabel(self.frame)
        self.comp_icon.setGeometry(QtCore.QRect(20, 200, 41, 61))
        self.comp_icon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comp_icon.setStyleSheet("background-color: none;")
        self.comp_icon.setText("")
        self.comp_icon.setPixmap(QtGui.QPixmap("images/important.png"))
        self.comp_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.comp_icon.setObjectName("comp_icon")
        self.calender1 = QtWidgets.QPushButton(self.frame)
        self.calender1.setGeometry(QtCore.QRect(0, 260, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.calender1.setFont(font)
        self.calender1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.calender1.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: #000000;\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(248, 248, 248);\n"
"}")
        self.calender1.setObjectName("calender1")
        self.about1 = QtWidgets.QPushButton(self.frame)
        self.about1.setGeometry(QtCore.QRect(0, 320, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.about1.setFont(font)
        self.about1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.about1.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: #000000;\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(248, 248, 248);\n"
"}")
        self.about1.setObjectName("about1")
        self.abo_icon = QtWidgets.QLabel(self.frame)
        self.abo_icon.setGeometry(QtCore.QRect(20, 320, 41, 61))
        self.abo_icon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.abo_icon.setStyleSheet("background-color: none;")
        self.abo_icon.setText("")
        self.abo_icon.setPixmap(QtGui.QPixmap("images/personal.png"))
        self.abo_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.abo_icon.setObjectName("abo_icon")
        self.cal_icon = QtWidgets.QLabel(self.frame)
        self.cal_icon.setGeometry(QtCore.QRect(20, 260, 41, 61))
        self.cal_icon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cal_icon.setStyleSheet("background-color: none;")
        self.cal_icon.setText("")
        self.cal_icon.setPixmap(QtGui.QPixmap("images/calender_icon.png"))
        self.cal_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.cal_icon.setObjectName("cal_icon")
        self.label_6 = QtWidgets.QLabel(self.day)
        self.label_6.setGeometry(QtCore.QRect(340, 0, 941, 851))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("images/bak_day.jpg"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.day)
        self.label_7.setGeometry(QtCore.QRect(380, 40, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(21)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.date = QtWidgets.QLabel(self.day)
        self.date.setGeometry(QtCore.QRect(380, 90, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.date.setFont(font)
        self.date.setStyleSheet("color: rgb(255, 255, 255);")
        self.date.setObjectName("date")
        self.frame_focus = QtWidgets.QLabel(self.day)
        self.frame_focus.setGeometry(QtCore.QRect(360, 220, 661, 391))
        self.frame_focus.setText("")
        self.frame_focus.setPixmap(QtGui.QPixmap("images/bak_day.png"))
        self.frame_focus.setObjectName("frame_focus")
        self.calender_img = QtWidgets.QLabel(self.day)
        self.calender_img.setGeometry(QtCore.QRect(650, 240, 331, 201))
        self.calender_img.setText("")
        self.calender_img.setPixmap(QtGui.QPixmap("images/calender.png"))
        self.calender_img.setObjectName("calender_img")
        self.label_focus = QtWidgets.QLabel(self.day)
        self.label_focus.setGeometry(QtCore.QRect(720, 430, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_focus.setFont(font)
        self.label_focus.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_focus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_focus.setObjectName("label_focus")
        self.label_things = QtWidgets.QLabel(self.day)
        self.label_things.setGeometry(QtCore.QRect(650, 500, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_things.setFont(font)
        self.label_things.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_things.setAlignment(QtCore.Qt.AlignCenter)
        self.label_things.setObjectName("label_things")
        self.label_every = QtWidgets.QLabel(self.day)
        self.label_every.setGeometry(QtCore.QRect(650, 530, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_every.setFont(font)
        self.label_every.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_every.setAlignment(QtCore.Qt.AlignCenter)
        self.label_every.setObjectName("label_every")
        self.addtask = QtWidgets.QLineEdit(self.day)
        self.addtask.setGeometry(QtCore.QRect(420, 750, 781, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.addtask.setFont(font)
        self.addtask.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.addtask.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(251, 226, 255);")
        self.addtask.setAlignment(QtCore.Qt.AlignCenter)
        self.addtask.setObjectName("addtask")
        self.close1 = QtWidgets.QPushButton(self.day)
        self.close1.setGeometry(QtCore.QRect(1240, 10, 31, 31))
        self.close1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close1.setStyleSheet("QPushButton {\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(148, 80, 157, 100);\n"
"    border-radius: 1px;\n"
"}")
        self.close1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close1.setIcon(icon)
        self.close1.setIconSize(QtCore.QSize(36, 37))
        self.close1.setObjectName("close1")
        self.mini1 = QtWidgets.QPushButton(self.day)
        self.mini1.setGeometry(QtCore.QRect(1200, 10, 31, 31))
        self.mini1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mini1.setStyleSheet("QPushButton {\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(148, 80, 157, 100);\n"
"    border-radius: 1px;\n"
"}")
        self.mini1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/mini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mini1.setIcon(icon1)
        self.mini1.setIconSize(QtCore.QSize(36, 37))
        self.mini1.setObjectName("mini1")
        self.plus_label = QtWidgets.QLabel(self.day)
        self.plus_label.setGeometry(QtCore.QRect(420, 755, 55, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(29)
        self.plus_label.setFont(font)
        self.plus_label.setStyleSheet("color: rgb(113, 113, 113);")
        self.plus_label.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_label.setObjectName("plus_label")
        self.submit = QtWidgets.QPushButton(self.day)
        self.submit.setGeometry(QtCore.QRect(1140, 750, 41, 61))
        self.submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit.setStyleSheet("background-color: none;\n"
"")
        self.submit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/submit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submit.setIcon(icon2)
        self.submit.setIconSize(QtCore.QSize(36, 37))
        self.submit.setObjectName("submit")
        self.stackedWidget.addWidget(self.day)
        self.day_task = QtWidgets.QWidget()
        self.day_task.setStyleSheet("border-radius: 2px;")
        self.day_task.setObjectName("day_task")
        self.myday_title = QtWidgets.QLabel(self.day_task)
        self.myday_title.setGeometry(QtCore.QRect(380, 40, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(21)
        self.myday_title.setFont(font)
        self.myday_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.myday_title.setObjectName("myday_title")
        self.label_29 = QtWidgets.QLabel(self.day_task)
        self.label_29.setGeometry(QtCore.QRect(340, 0, 941, 851))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("images/bak_day.jpg"))
        self.label_29.setObjectName("label_29")
        self.mini2 = QtWidgets.QPushButton(self.day_task)
        self.mini2.setGeometry(QtCore.QRect(1200, 10, 31, 31))
        self.mini2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mini2.setStyleSheet("QPushButton {\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(148, 80, 157, 100);\n"
"}")
        self.mini2.setText("")
        self.mini2.setIcon(icon1)
        self.mini2.setIconSize(QtCore.QSize(36, 37))
        self.mini2.setObjectName("mini2")
        self.addtask_3 = QtWidgets.QLineEdit(self.day_task)
        self.addtask_3.setGeometry(QtCore.QRect(420, 750, 781, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.addtask_3.setFont(font)
        self.addtask_3.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(251, 226, 255);")
        self.addtask_3.setAlignment(QtCore.Qt.AlignCenter)
        self.addtask_3.setObjectName("addtask_3")
        self.plus_label2 = QtWidgets.QLabel(self.day_task)
        self.plus_label2.setGeometry(QtCore.QRect(420, 755, 55, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(29)
        self.plus_label2.setFont(font)
        self.plus_label2.setStyleSheet("color: rgb(113, 113, 113);")
        self.plus_label2.setAlignment(QtCore.Qt.AlignCenter)
        self.plus_label2.setObjectName("plus_label2")
        self.frame_3 = QtWidgets.QFrame(self.day_task)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 341, 861))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.nameapp2 = QtWidgets.QLabel(self.frame_3)
        self.nameapp2.setGeometry(QtCore.QRect(20, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        self.nameapp2.setFont(font)
        self.nameapp2.setStyleSheet("color: rgb(91, 91, 91);")
        self.nameapp2.setObjectName("nameapp2")
        self.profile2 = QtWidgets.QLabel(self.frame_3)
        self.profile2.setGeometry(QtCore.QRect(20, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.profile2.setFont(font)
        self.profile2.setStyleSheet("background-color: #00a300;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.profile2.setAlignment(QtCore.Qt.AlignCenter)
        self.profile2.setObjectName("profile2")
        self.nameuser2 = QtWidgets.QLabel(self.frame_3)
        self.nameuser2.setGeometry(QtCore.QRect(70, 70, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        self.nameuser2.setFont(font)
        self.nameuser2.setObjectName("nameuser2")
        self.myday2 = QtWidgets.QPushButton(self.frame_3)
        self.myday2.setGeometry(QtCore.QRect(0, 140, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.myday2.setFont(font)
        self.myday2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.myday2.setStyleSheet("border: 0px;\n"
"color: #647783;\n"
"background-color: rgb(248, 249, 250, 200);")
        self.myday2.setObjectName("myday2")
        self.my_icon2 = QtWidgets.QLabel(self.frame_3)
        self.my_icon2.setGeometry(QtCore.QRect(20, 140, 41, 61))
        self.my_icon2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.my_icon2.setStyleSheet("background-color: none;")
        self.my_icon2.setText("")
        self.my_icon2.setPixmap(QtGui.QPixmap("images/my day.png"))
        self.my_icon2.setAlignment(QtCore.Qt.AlignCenter)
        self.my_icon2.setObjectName("my_icon2")
        self.show_pag_select2 = QtWidgets.QLabel(self.frame_3)
        self.show_pag_select2.setGeometry(QtCore.QRect(10, 140, 21, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        self.show_pag_select2.setFont(font)
        self.show_pag_select2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.show_pag_select2.setStyleSheet("color: #647783;\n"
"background-color: none;")
        self.show_pag_select2.setObjectName("show_pag_select2")
        self.comp2 = QtWidgets.QPushButton(self.frame_3)
        self.comp2.setGeometry(QtCore.QRect(0, 200, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.comp2.setFont(font)
        self.comp2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comp2.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: #000000;\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(248, 248, 248);\n"
"}")
        self.comp2.setObjectName("comp2")
        self.comp_icon2 = QtWidgets.QLabel(self.frame_3)
        self.comp_icon2.setGeometry(QtCore.QRect(20, 200, 41, 61))
        self.comp_icon2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comp_icon2.setStyleSheet("background-color: none;")
        self.comp_icon2.setText("")
        self.comp_icon2.setPixmap(QtGui.QPixmap("images/important.png"))
        self.comp_icon2.setAlignment(QtCore.Qt.AlignCenter)
        self.comp_icon2.setObjectName("comp_icon2")
        self.calender2 = QtWidgets.QPushButton(self.frame_3)
        self.calender2.setGeometry(QtCore.QRect(0, 260, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.calender2.setFont(font)
        self.calender2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.calender2.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: #000000;\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(248, 248, 248);\n"
"}")
        self.calender2.setObjectName("calender2")
        self.about2 = QtWidgets.QPushButton(self.frame_3)
        self.about2.setGeometry(QtCore.QRect(0, 320, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.about2.setFont(font)
        self.about2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.about2.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: #000000;\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(248, 248, 248);\n"
"}")
        self.about2.setObjectName("about2")
        self.abo_icon2 = QtWidgets.QLabel(self.frame_3)
        self.abo_icon2.setGeometry(QtCore.QRect(20, 320, 41, 61))
        self.abo_icon2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.abo_icon2.setStyleSheet("background-color: none;")
        self.abo_icon2.setText("")
        self.abo_icon2.setPixmap(QtGui.QPixmap("images/personal.png"))
        self.abo_icon2.setAlignment(QtCore.Qt.AlignCenter)
        self.abo_icon2.setObjectName("abo_icon2")
        self.cal_icon2 = QtWidgets.QLabel(self.frame_3)
        self.cal_icon2.setGeometry(QtCore.QRect(20, 260, 41, 61))
        self.cal_icon2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.cal_icon2.setStyleSheet("background-color: none;")
        self.cal_icon2.setText("")
        self.cal_icon2.setPixmap(QtGui.QPixmap("images/calender_icon.png"))
        self.cal_icon2.setAlignment(QtCore.Qt.AlignCenter)
        self.cal_icon2.setObjectName("cal_icon2")
        self.date2 = QtWidgets.QLabel(self.day_task)
        self.date2.setGeometry(QtCore.QRect(380, 90, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.date2.setFont(font)
        self.date2.setStyleSheet("color: rgb(255, 255, 255);")
        self.date2.setObjectName("date2")
        self.close2 = QtWidgets.QPushButton(self.day_task)
        self.close2.setGeometry(QtCore.QRect(1240, 10, 31, 31))
        self.close2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close2.setStyleSheet("QPushButton {\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(148, 80, 157, 100);\n"
"}")
        self.close2.setText("")
        self.close2.setIcon(icon)
        self.close2.setIconSize(QtCore.QSize(36, 37))
        self.close2.setObjectName("close2")
        self.task1 = QtWidgets.QLabel(self.day_task)
        self.task1.setGeometry(QtCore.QRect(380, 130, 861, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.task1.setFont(font)
        self.task1.setStyleSheet("background-color: rgb(255, 213, 246, 150);\n"
"color: rgb(10, 10, 10);\n"
"border-radius: 7px;")
        self.task1.setText("")
        self.task1.setAlignment(QtCore.Qt.AlignCenter)
        self.task1.setObjectName("task1")
        self.task2 = QtWidgets.QLabel(self.day_task)
        self.task2.setGeometry(QtCore.QRect(380, 200, 861, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.task2.setFont(font)
        self.task2.setStyleSheet("background-color: rgb(255, 213, 246, 150);\n"
"color: rgb(10, 10, 10);\n"
"border-radius: 7px;")
        self.task2.setText("")
        self.task2.setAlignment(QtCore.Qt.AlignCenter)
        self.task2.setObjectName("task2")
        self.task4 = QtWidgets.QLabel(self.day_task)
        self.task4.setGeometry(QtCore.QRect(380, 340, 861, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.task4.setFont(font)
        self.task4.setStyleSheet("background-color: rgb(255, 213, 246, 150);\n"
"color: rgb(10, 10, 10);\n"
"border-radius: 7px;")
        self.task4.setText("")
        self.task4.setAlignment(QtCore.Qt.AlignCenter)
        self.task4.setObjectName("task4")
        self.task3 = QtWidgets.QLabel(self.day_task)
        self.task3.setGeometry(QtCore.QRect(380, 270, 861, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.task3.setFont(font)
        self.task3.setStyleSheet("background-color: rgb(255, 213, 246, 150);\n"
"color: rgb(10, 10, 10);\n"
"border-radius: 7px;")
        self.task3.setText("")
        self.task3.setAlignment(QtCore.Qt.AlignCenter)
        self.task3.setObjectName("task3")
        self.task6 = QtWidgets.QLabel(self.day_task)
        self.task6.setGeometry(QtCore.QRect(380, 480, 861, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.task6.setFont(font)
        self.task6.setStyleSheet("background-color: rgb(255, 213, 246, 180);\n"
"color: rgb(10, 10, 10);\n"
"border-radius: 7px;")
        self.task6.setText("")
        self.task6.setAlignment(QtCore.Qt.AlignCenter)
        self.task6.setObjectName("task6")
        self.task8 = QtWidgets.QLabel(self.day_task)
        self.task8.setGeometry(QtCore.QRect(380, 620, 861, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.task8.setFont(font)
        self.task8.setStyleSheet("background-color: rgb(255, 213, 246, 180);\n"
"color: rgb(10, 10, 10);\n"
"border-radius: 7px;")
        self.task8.setText("")
        self.task8.setAlignment(QtCore.Qt.AlignCenter)
        self.task8.setObjectName("task8")
        self.task7 = QtWidgets.QLabel(self.day_task)
        self.task7.setGeometry(QtCore.QRect(380, 550, 861, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.task7.setFont(font)
        self.task7.setStyleSheet("background-color: rgb(255, 213, 246, 180);\n"
"color: rgb(10, 10, 10);\n"
"border-radius: 7px;")
        self.task7.setText("")
        self.task7.setAlignment(QtCore.Qt.AlignCenter)
        self.task7.setObjectName("task7")
        self.task5 = QtWidgets.QLabel(self.day_task)
        self.task5.setGeometry(QtCore.QRect(380, 410, 861, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.task5.setFont(font)
        self.task5.setStyleSheet("background-color: rgb(255, 213, 246, 150);\n"
"color: rgb(10, 10, 10);\n"
"border-radius: 7px;")
        self.task5.setText("")
        self.task5.setAlignment(QtCore.Qt.AlignCenter)
        self.task5.setObjectName("task5")
        self.sub1 = QtWidgets.QPushButton(self.day_task)
        self.sub1.setGeometry(QtCore.QRect(390, 130, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        self.sub1.setFont(font)
        self.sub1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sub1.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: rgb(127, 127, 127);\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(170, 255, 255);\n"
"}")
        self.sub1.setIconSize(QtCore.QSize(36, 37))
        self.sub1.setObjectName("sub1")
        self.sub2 = QtWidgets.QPushButton(self.day_task)
        self.sub2.setGeometry(QtCore.QRect(390, 200, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        self.sub2.setFont(font)
        self.sub2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sub2.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: rgb(127, 127, 127);\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(170, 255, 255);\n"
"}")
        self.sub2.setIconSize(QtCore.QSize(36, 37))
        self.sub2.setObjectName("sub2")
        self.sub4 = QtWidgets.QPushButton(self.day_task)
        self.sub4.setGeometry(QtCore.QRect(390, 340, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        self.sub4.setFont(font)
        self.sub4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sub4.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: rgb(127, 127, 127);\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(170, 255, 255);\n"
"}")
        self.sub4.setIconSize(QtCore.QSize(36, 37))
        self.sub4.setObjectName("sub4")
        self.sub3 = QtWidgets.QPushButton(self.day_task)
        self.sub3.setGeometry(QtCore.QRect(390, 270, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        self.sub3.setFont(font)
        self.sub3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sub3.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: rgb(127, 127, 127);\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(170, 255, 255);\n"
"}")
        self.sub3.setIconSize(QtCore.QSize(36, 37))
        self.sub3.setObjectName("sub3")
        self.sub7 = QtWidgets.QPushButton(self.day_task)
        self.sub7.setGeometry(QtCore.QRect(390, 550, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        self.sub7.setFont(font)
        
